language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=sbcl
    - LISP=ccl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh  

before_script:
  - echo "(defsystem :dummy-cl-travis-system)" > ~/lisp/dummy-cl-travis-system.asd

script:
  - cl -l cl-hipchat -l prove
       -e '(progn
            (setf prove:*debug-on-error* t
                  *debugger-hook* (lambda (c h)
                                    (declare (ignore c h))
                                    (uiop:quit -1)))
            (or (prove:run :cl-hipchat-test)
                (uiop:quit -1)))'